sudo: required

services:
  - docker
  
script:
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASS";

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    tags: true
